# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/openstack-dev/bashate
    rev: 2.0.0
    hooks:
    -   id: bashate
        entry: bashate --error . --verbose --ignore=E006,E040
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-l, --recursive]
        files: .py$
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: rst-backticks
-   repo: local
    hooks:
      - id: sphinx-build
        name: sphinx build
        entry: python3.5 -m sphinx.cmd.build
        args: [-a, -E, source, build]
        language: system
        files: ^source/
        types: [file]
        pass_filenames: false
